# Get voting data for individual votes in the House & Senate

# XML conversion base code generated by Chat GPT

import requests
import pandas as pd
import xml.etree.ElementTree as ET
from io import BytesIO
import os
import shutil
from pathlib import Path
import time

# Change directory
os.chdir('code/data')


def getting_voting_data_from_xml_urls(xml_base_url, csv_output_name, chamber):
    print("Getting data for", csv_output_name)

    session = requests.Session()
    session.headers.update({
        "User-Agent": ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                       "AppleWebKit/537.36 (KHTML, like Gecko) "
                       "Chrome/120.0 Safari/537.36")
    })
    rows = []
    delay_between_requests = 0.8
    max_backoff = 60

    # Looping through to gather all valid urls
    for i in range(1, 1000):  # safety upper bound
        url = xml_base_url.format(i)

        # Handling rate limits
        backoff = 2
        while True:
            r = session.get(url)

            if r.status_code == 403:
                print(f"403 received, backing off {backoff}s: {url}")
                time.sleep(backoff)
                backoff = min(backoff * 2, max_backoff)
                continue
            break

        if r.status_code == 404:
            print("404 recieved at: ", url)
            break

        r.raise_for_status()

        # Parse XML from memory (no file write)
        try:
            tree = ET.parse(BytesIO(r.content))
        except ET.ParseError:
            break

        root = tree.getroot()

        # Constructing csv from xml files
        if chamber == "House":
            roll_number = root.findtext(".//rollcall-num")
            bill = root.findtext(".//legis-num")
            date = root.findtext(".//action-date")

            for vote in root.findall(".//recorded-vote"):
                legislator = vote.find("legislator")

                rows.append({
                    "roll_number": roll_number,
                    "bill": bill,
                    "date": date,
                    "member": legislator.text,
                    "member_id": legislator.attrib.get("name-id"),
                    "vote": vote.findtext("vote")
                })
        if chamber == "Senate":
            roll_number = root.findtext(".//vote_number")
            bill = root.findtext(".//document/document_name")
            date = root.findtext(".//vote_date")

            for vote in root.findall(".//members/member"):
                rows.append({
                    "roll_number": roll_number,
                    "bill": bill,
                    "date": date,
                    "member": f"{vote.findtext('first_name')} {vote.findtext('last_name')}",
                    "member_id": vote.findtext("lis_member_id"),
                    "vote": vote.findtext("vote_cast")
                })
        time.sleep(delay_between_requests)
    
    df = pd.DataFrame(rows)
    df.to_csv(f"silver/{csv_output_name}", index=False)

# Delete later
# congress=119
# session=2
# senate_base_url = f"https://www.senate.gov/legislative/LIS/roll_call_votes/vote{congress}{session}/vote_{congress}_{session}_00{{:03d}}.xml"
# senate_output_json = f"senate_votes_{congress}_{session}.json"
# getting_voting_data_from_xml_urls(senate_base_url, senate_output_json, "Senate")

# For loop for getting data

# 119th Congress (to-do: increase Congress)
for i in range (1):
    congress = 119-i

    # For sessions 1 & 2
    for j in range(2):
        session = j+1
        year = 1786+congress*2 + session

        senate_base_url = f"https://www.senate.gov/legislative/LIS/roll_call_votes/vote{congress}{session}/vote_{congress}_{session}_00{{:03d}}.xml"
        senate_output_json = f"senate_votes_{congress}_{session}.json"

        house_base_url = f"https://clerk.house.gov/evs/{year}/roll{{:03d}}.xml"
        house_output_json = f"house_votes_{congress}_{session}.json"
        
        # Limit function call to most recent data or new historical data
        if (
            (congress == 119 and session == 2)
            or not os.path.isfile(f"silver/{senate_output_json}")
            or not os.path.isfile(f"silver/{house_output_json}")
        ):
            getting_voting_data_from_xml_urls(senate_base_url, senate_output_json, "Senate")
            getting_voting_data_from_xml_urls(house_base_url, house_output_json, "House")